### PR TITLE
add frozen version plugins logic

### PR DESCRIPTION
**Pull request by fyears**
So here is the implementation of the ideas from https://github.com/TfTHacker/obsidian42-brat/pull/32 .

The basic idea is adding `pluginSubListFrozenVersion` inside `data.json`, that is a sub list of `pluginList`. and add the corresponding logic of skipping items in sub list while updating any beta plugins.

### CODE REVIEW

**Comment by fyears** [comment]
ref: https://github.com/TfTHacker/obsidian42-brat/issues/30

**Comment by fyears** [comment]
Admittedly the logic is not very simple, basically because the `addPlugin` function mixes the install and update logics originally. Hopefully I have dealt with all the corner cases correctly...

**Comment by TfTHacker** [comment]
I finished reviewing and will accept the pull request. I am just waiting for a confirmation on a bug. i updated the esbuild version. In the past this caused issues for some users. I am hoping it is now resolved. So I might wait a day to pull this in just to make sure BRAT is stable with 0.6.33

I am debating whether we need to add the "without frozen" versions to the update. Perthaps if it is documented as you did it will be clear the distinction.

I also tested this one repo and it worked, but it didn't work with one repo. The repo is: https://github.com/kzhovn/copy-command-obsidian and was trying release 0.1.0 and 0.1.1. Do you want to give it a try and see if it works for you?

**Comment by fyears** [comment]
> The repo is: https://github.com/kzhovn/copy-command-obsidian and was trying release 0.1.0 and 0.1.1.

I I tested the process on a Windows machine, and confirmed that I count install these two versions without problem.

**Comment by TfTHacker** [comment]
So I got feedback that the esbuild issue was resolved, so I feel good about doing the PR merge. Will test as well and tweak a bit. Looking forward to publishing this.

**Comment by fyears** [comment]
Cool! Looking forward to it, haha!

**Pull request merged**
