### PR TITLE
feat: access for private repo

### PR DESCRIPTION
**Pull request by HananoshikaYomaru**
This implement #64 

CleanShot 2024-01-10 at 14 49 40@2x

This is implemented by using the GitHub API. If the repo is private, this will use the Github API instead of the browser download url. This operation require user to create a personal access token.

### CODE REVIEW

**Comment by TfTHacker** [comment]
This is amazing. can you provide me with a link to the docs for the API? I need to review this a little, but excited to add this. Amazing work!

**Comment by HananoshikaYomaru** [comment]
https://docs.github.com/en/rest/releases/assets?apiVersion=2022-11-28

**Review by TfTHacker — COMMENTED** [review]
One other question, What instructions should be provided for a user to get their token. I am assuming some users of BRAT have no experience. So:

1) What URL can we direct them to where they create the token? (or get instructions)

2) Are there specific permissions that need to be enabled for this to work?

**Comment by HananoshikaYomaru** [comment]
you can put the instruction in a new section of read me

1. they need to go to setting > Developer setting > Personal access token
2. create a new token 
3. set the persmission of repo to the one they want to access or just every repo 
4. set the content to be at least `read-only` 

CleanShot 2024-01-14 at 19 29 23@2x

CleanShot 2024-01-14 at 19 29 35@2x

CleanShot 2024-01-14 at 19 29 49@2x

CleanShot 2024-01-14 at 19 30 46@2x

**Comment by TfTHacker** [comment]
Thank you for this. I will be working away at it as I can, I am a bit backlogged, but would like to get this out ASAP as a beta tot he public.

**Comment by HananoshikaYomaru** [comment]
I have tested by myself because I have some private plugins, but I strongly asking someone to test it too.

**Comment by TfTHacker** [comment]
I am going to push this out for testing. It is a nice feature, thank you for adding it.

**Comment by TfTHacker** [comment]
I'm embarrassed to say that I'm only now getting around to rolling this out. I was swamped at work, but I've wrapped up my testing and will work on some documentation. Then, I can make this available for public release.

**Comment by TfTHacker** [comment]
This is now live; let us see what breaks :-)

I put together some very rudimentary documentation. Feedback welcome!

https://tfthacker.com/brat-private-repo

**Pull request merged**
