### PR TITLE
Feat: enable beta plugin installation via Obsidian protocol

### PR DESCRIPTION
**Pull request by RyotaUshio**
Hi, thank you so much for maintaining this important infrastructure for the Obsidian community!

I've been wondering it might be great if I could add a button to README or the docs of my beta plugin that allows us to easily install the plugin by just clicking it. So I added an Obsidian protocol handler. Please let me know if you have any suggestions.

Example: 

```
[<button>Install via BRAT</button>](obsidian://brat?plugin=RyotaUshio/obsidian-enhanced-link-suggestions)
```

or 

```
[<button>Install via BRAT</button>](obsidian://brat?plugin=https://github.com/RyotaUshio/obsidian-enhanced-link-suggestions)
```

https://github.com/TfTHacker/obsidian42-brat/assets/72342591/16d5ca7f-4f0c-4e5f-b3f9-6536a217a16f

### CODE REVIEW

**Comment by TfTHacker** [comment]
This is an amazing idea. Wish I had thought of it. Thank you for the submission. Let me do a little testing and we can get this out to the public.

**Comment by TfTHacker** [comment]
So this is great. Let me ask a question. Perhaps I should add a prompt to the user to confirm they want to do the installation. That way a button doesn't accidentally get clicked and suddenly you have some funny code on your machine. What do you think?

**Comment by TfTHacker** [comment]
also please DM me on discord.

**Comment by RyotaUshio** [comment]
In most case, users will click a `obsidian://brat` link outside Obsidian. In that case, browsers will show the user a confirmation popup like this.

image

So I think users might find it redundant if we add some modal like "Are you sure you want to install ...?". But having that option will be definitely nice. So how about showing the confirmation modal when a user opens a `obsidian://brat..` link for the first time, and add a checkbox saying "Don't ask me again" to it?

**Comment by TfTHacker** [comment]
I was looking at how Obsidian does this from their site using their install feature. It loads Obsidian into the plugins install screen, so user still has to click install. It seems like a reasonable safety precaution.

What could be done is load the "Brat: Add plugin" modal with the URL sent through the protocol. So it basically brings the person to where they would add a plugin manually, but populated with the plugin github. URL and then press install button.

**Comment by RyotaUshio** [comment]
I see, that makes a lot of sense! I sent a new PR that implements your idea.

**Pull request merged**
